# Generated by Django 3.0.8 on 2020-07-27 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0002_auto_20200710_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_fi',
        ),
    ]
